### ISSUE TITLE
spnav_cfg_set_repeat not declared

### ISSUE THREAD

**Issue by vrhinehart** [FreeSpacenav/spnavcfg#55]
Attempting to build on Ubuntu 24.04 LTS with libspnav version 1.1 installed via Brew and detected by pkg-config. The following error appears during make: 

`g++ -pedantic -Wall -g -O3 -I. -I/usr/local/include -fPIC -std=c++11 -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtGui -DQT_WIDGETS_LIB -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -DQT_GUI_LIB -DQT_CORE_LIB   -MMD   -c -o src/ui.o src/ui.cc
src/ui.cc: In member function ‘void MainWin::spin_changed(int)’:
src/ui.cc:466:17: error: ‘spnav_cfg_set_repeat’ was not declared in this scope; did you mean ‘spnav_cfg_set_serial’?
  466 |                 spnav_cfg_set_repeat(cfg.repeat);
      |                 ^~~~~~~~~~~~~~~~~~~~
      |                 spnav_cfg_set_serial
src/ui.cc: In member function ‘void MainWin::chk_changed(int)’:
src/ui.cc:514:17: error: ‘spnav_cfg_set_repeat’ was not declared in this scope; did you mean ‘spnav_cfg_set_serial’?
  514 |                 spnav_cfg_set_repeat(cfg.repeat);
      |                 ^~~~~~~~~~~~~~~~~~~~
      |                 spnav_cfg_set_serial
make: *** [<builtin>: src/ui.o] Error 1
rm src/ui.moc.cc
`
Unsure what would cause this issue, given up to date libspnav is installed and no other versions are present.

**Comment by jtsiomb** [comment]
libspnav 1.1 does not have `spnav_cfg_set_repeat`. It was added in libspnav 1.2.

**Comment by vrhinehart** [comment]
@jtsiomb I was able to get it to compile by removing libspnav and compiling it from source instead. Now however, I get the following runtime error. 

`spnavcfg: symbol lookup error: spnavcfg: undefined symbol: spnav_cfg_set_repeat`

pkg-config reports the following version of libspnav installed `1.2-3-gbcc2e29`

**Comment by jtsiomb** [comment]
There's probably an older version of libspnav still installed somewhere and the dynamic loader finds that one at runtime. Remove any old versions and also run ldconfig.

**Comment by vrhinehart** [comment]
Just running ldconfig sorted it out, thanks!
